name: Build and Push Docker Images
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
    name: node-dev-base ${{ matrix.node }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build nystudio107/node-dev-base:${{ matrix.node }}-alpine
        uses: docker/build-push-action@v2
        with:
          context: node-dev-base/node-${{ matrix.node }}-alpine
          file: node-dev-base/node-${{ matrix.node }}-alpine/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nystudio107/node-dev-base:${{ matrix.node }}-alpine
          build-args: |
            NODE_VERSION=${{ matrix.node }}
